### ISSUE TITLE
Max line length

### ISSUE THREAD

**Issue by grahamwren** [az0977776/cs4500-a1p1#1]
Hello,

We've been writing a fuzzer for benchmarking your `sorer` and have discovered you have a max line length of 4096.
https://github.com/az0977776/cs4500-a1p1/blob/d91da9986d94fcfcddcb9149f6189b5efb949693/sorer.h#L12

It's not clear where you found this in the spec, but in order to increase parse load, we are providing lines up to 10000 bytes. If there was somewhere in the spec which dictates a max line length we will update our sor file generation script. Otherwise, I would suggest you increase this buffer size significantly to handle lines up to 1MB.

**Comment by az0977776** [comment]
This was not in the spec, but we had to choose a number and went with 4096 (page size). We will not make this change as other groups might have already ran their tests on our adapter and it is late into the week

**Comment by grahamwren** [comment]
Okay, we will apply a patch to your repo to benchmark it.
